export const COUNTRIES: string[] = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda",
  "Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain",
  "Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan",
  "Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria",
  "Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde",
  "Central African Republic","Chad","Chile","China","Colombia","Comoros",
  "Congo (Republic of)","Costa Rica","Côte d'Ivoire","Croatia","Cuba","Cyprus",
  "Czech Republic","DR Congo","Denmark","Djibouti","Dominica","Dominican Republic",
  "Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia",
  "Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia",
  "Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau",
  "Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran",
  "Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan",
  "Kenya","Kiribati","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon",
  "Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg",
  "Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands",
  "Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia",
  "Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal",
  "Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea",
  "North Macedonia","Norway","Oman","Pakistan","Palau","Palestine","Panama",
  "Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar",
  "Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia",
  "Saint Vincent and the Grenadines","Samoa","San Marino","São Tomé and Príncipe",
  "Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore",
  "Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea",
  "South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland",
  "Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo",
  "Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu",
  "Uganda","Ukraine","United Arab Emirates","United Kingdom","United States",
  "Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam",
  "Yemen","Zambia","Zimbabwe",
];

export const CITY_MAP: Record<string, string[]> = {
  "Afghanistan": ["Kabul","Kandahar","Herat","Mazar-i-Sharif","Jalalabad","Kunduz","Ghazni","Balkh"],
  "Albania": ["Tirana","Durrës","Vlorë","Shkodër","Fier","Korçë","Elbasan","Berat"],
  "Algeria": ["Algiers","Oran","Constantine","Annaba","Blida","Batna","Sétif","Sidi Bel Abbès","Biskra","Tlemcen"],
  "Andorra": ["Andorra la Vella","Escaldes-Engordany","Encamp"],
  "Angola": ["Luanda","Huambo","Lobito","Benguela","Lubango","Malanje","Cabinda","Soyo"],
  "Antigua and Barbuda": ["St. John's","All Saints","Liberta","Potters Village"],
  "Argentina": ["Buenos Aires","Córdoba","Rosario","Mendoza","La Plata","Tucumán","Mar del Plata","Salta","Santa Fe","San Juan","Resistencia","Neuquén","Bahía Blanca","Corrientes","Posadas"],
  "Armenia": ["Yerevan","Gyumri","Vanadzor","Vagharshapat","Abovyan","Kapan","Hrazdan"],
  "Australia": ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Gold Coast","Newcastle","Canberra","Sunshine Coast","Wollongong","Hobart","Geelong","Townsville","Cairns","Darwin","Toowoomba"],
  "Austria": ["Vienna","Graz","Linz","Salzburg","Innsbruck","Klagenfurt","Villach","Wels","Sankt Pölten","Dornbirn"],
  "Azerbaijan": ["Baku","Ganja","Sumqayit","Mingachevir","Nakhchivan","Lankaran","Shirvan","Shaki"],
  "Bahamas": ["Nassau","Freeport","West End","Coopers Town","Marsh Harbour"],
  "Bahrain": ["Manama","Riffa","Muharraq","Hamad Town","A'ali","Isa Town","Sitra"],
  "Bangladesh": ["Dhaka","Chittagong","Khulna","Rajshahi","Sylhet","Comilla","Rangpur","Mymensingh","Narayanganj","Jessore","Barishal"],
  "Barbados": ["Bridgetown","Speightstown","Oistins","Bathsheba","Holetown"],
  "Belarus": ["Minsk","Gomel","Mogilev","Vitebsk","Grodno","Brest","Babruysk","Baranovichi","Borisov","Pinsk"],
  "Belgium": ["Brussels","Antwerp","Ghent","Charleroi","Liège","Bruges","Namur","Leuven","Mons","Mechelen"],
  "Belize": ["Belize City","Belmopan","San Ignacio","Orange Walk","Dangriga","Corozal"],
  "Benin": ["Cotonou","Porto-Novo","Parakou","Djougou","Bohicon","Kandi","Lokossa"],
  "Bhutan": ["Thimphu","Phuntsholing","Paro","Punakha","Samdrup Jongkhar","Gelephu"],
  "Bolivia": ["Santa Cruz de la Sierra","La Paz","Cochabamba","Oruro","Sucre","Potosí","Tarija","Trinidad"],
  "Bosnia and Herzegovina": ["Sarajevo","Banja Luka","Tuzla","Zenica","Mostar","Bijeljina","Brčko"],
  "Botswana": ["Gaborone","Francistown","Molepolole","Serowe","Maun","Kanye","Mahalapye"],
  "Brazil": ["São Paulo","Rio de Janeiro","Brasília","Salvador","Fortaleza","Belo Horizonte","Manaus","Curitiba","Recife","Goiânia","Porto Alegre","Belém","Guarulhos","Campinas","São Luís","Maceió","Natal","Teresina","Campo Grande","João Pessoa"],
  "Brunei": ["Bandar Seri Begawan","Kuala Belait","Seria","Tutong","Bangar"],
  "Bulgaria": ["Sofia","Plovdiv","Varna","Burgas","Ruse","Stara Zagora","Pleven","Sliven","Dobrich","Shumen"],
  "Burkina Faso": ["Ouagadougou","Bobo-Dioulasso","Koudougou","Banfora","Ouahigouya","Kaya"],
  "Burundi": ["Gitega","Bujumbura","Muyinga","Ruyigi","Ngozi","Rumonge"],
  "Cambodia": ["Phnom Penh","Siem Reap","Battambang","Sihanoukville","Kampong Cham","Kampong Thom","Pursat"],
  "Cameroon": ["Yaoundé","Douala","Garoua","Bamenda","Maroua","Bafoussam","Ngaoundéré","Bertoua"],
  "Canada": ["Toronto","Montreal","Vancouver","Calgary","Edmonton","Ottawa","Mississauga","Winnipeg","Quebec City","Hamilton","Halifax","Victoria","Surrey","Brampton","Kelowna","London","Windsor","Saskatoon"],
  "Cape Verde": ["Praia","Mindelo","Santa Maria","Assomada","Pedra Badejo"],
  "Central African Republic": ["Bangui","Bimbo","Mbaïki","Berberati","Kaga-Bandoro","Bambari"],
  "Chad": ["N'Djamena","Moundou","Sarh","Abéché","Kélo","Koumra"],
  "Chile": ["Santiago","Valparaíso","Concepción","La Serena","Antofagasta","Temuco","Rancagua","Talca","Arica","Iquique","Puerto Montt"],
  "China": ["Shanghai","Beijing","Guangzhou","Shenzhen","Chengdu","Hangzhou","Wuhan","Xi'an","Nanjing","Tianjin","Suzhou","Qingdao","Dongguan","Zhengzhou","Shenyang","Ningbo","Foshan","Kunming","Hefei","Changsha","Jinan","Harbin","Xiamen","Zhongshan","Wuxi"],
  "Colombia": ["Bogotá","Medellín","Cali","Barranquilla","Cartagena","Cúcuta","Bucaramanga","Pereira","Manizales","Santa Marta","Ibagué","Pasto"],
  "Comoros": ["Moroni","Mutsamudu","Fomboni","Domoni"],
  "Congo (Republic of)": ["Brazzaville","Pointe-Noire","Dolisie","Nkayi","Impfondo"],
  "Costa Rica": ["San José","Alajuela","Cartago","Heredia","Liberia","Limón","Paraíso"],
  "Côte d'Ivoire": ["Abidjan","Bouaké","Daloa","Yamoussoukro","San-Pédro","Korhogo","Man"],
  "Croatia": ["Zagreb","Split","Rijeka","Osijek","Zadar","Slavonski Brod","Pula","Karlovac"],
  "Cuba": ["Havana","Santiago de Cuba","Camagüey","Holguín","Guantánamo","Santa Clara","Las Tunas","Bayamo"],
  "Cyprus": ["Nicosia","Limassol","Larnaca","Paphos","Famagusta","Kyrenia","Paralimni"],
  "Czech Republic": ["Prague","Brno","Ostrava","Plzeň","Liberec","Olomouc","Ústí nad Labem","Hradec Králové","České Budějovice","Pardubice"],
  "DR Congo": ["Kinshasa","Lubumbashi","Mbuji-Mayi","Kananga","Kisangani","Goma","Bukavu","Tshikapa"],
  "Denmark": ["Copenhagen","Aarhus","Odense","Aalborg","Esbjerg","Randers","Kolding","Horsens","Vejle","Roskilde"],
  "Djibouti": ["Djibouti City","Ali Sabieh","Dikhil","Obock","Tadjourah"],
  "Dominica": ["Roseau","Portsmouth","Marigot","Berekua"],
  "Dominican Republic": ["Santo Domingo","Santiago de los Caballeros","La Romana","San Pedro de Macorís","Puerto Plata","La Vega","San Francisco de Macorís"],
  "Ecuador": ["Quito","Guayaquil","Cuenca","Santo Domingo","Ambato","Manta","Portoviejo","Loja","Machala","Durán"],
  "Egypt": ["Cairo","Alexandria","Giza","Shubra El Kheima","Port Said","Suez","Luxor","Mansoura","Tanta","Asyut","Ismailia","Faiyum"],
  "El Salvador": ["San Salvador","Santa Ana","San Miguel","Soyapango","Mejicanos","Apopa","Delgado","Ciudad Delgado"],
  "Equatorial Guinea": ["Malabo","Bata","Ebebiyín","Akonibe","Añisoc","Luba"],
  "Eritrea": ["Asmara","Keren","Massawa","Assab","Mendefera","Barentu"],
  "Estonia": ["Tallinn","Tartu","Narva","Pärnu","Kohtla-Järve","Viljandi","Rakvere","Kuressaare"],
  "Eswatini": ["Mbabane","Manzini","Lobamba","Big Bend","Mhlume"],
  "Ethiopia": ["Addis Ababa","Dire Dawa","Gondar","Mekelle","Adama","Hawassa","Bahir Dar","Jimma","Dessie","Jijiga"],
  "Fiji": ["Suva","Nadi","Lautoka","Labasa","Ba","Levuka"],
  "Finland": ["Helsinki","Espoo","Tampere","Vantaa","Turku","Oulu","Jyväskylä","Lahti","Kuopio","Kouvola"],
  "France": ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Montpellier","Strasbourg","Bordeaux","Lille","Rennes","Reims","Saint-Étienne","Toulon","Le Havre","Grenoble","Dijon","Angers"],
  "Gabon": ["Libreville","Port-Gentil","Franceville","Oyem","Moanda","Mouila"],
  "Gambia": ["Banjul","Serrekunda","Brikama","Bakau","Farafenni","Lamin"],
  "Georgia": ["Tbilisi","Batumi","Kutaisi","Rustavi","Zugdidi","Gori","Poti","Telavi"],
  "Germany": ["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Düsseldorf","Dortmund","Essen","Leipzig","Bremen","Dresden","Hanover","Nuremberg","Duisburg","Bochum","Wuppertal","Bielefeld","Bonn","Münster"],
  "Ghana": ["Accra","Kumasi","Tamale","Sekondi-Takoradi","Ashaiman","Sunyani","Cape Coast","Tema"],
  "Greece": ["Athens","Thessaloniki","Patras","Heraklion","Larissa","Volos","Ioannina","Chania","Chalcis","Kavala"],
  "Grenada": ["St. George's","Gouyave","Grenville","Victoria"],
  "Guatemala": ["Guatemala City","Quetzaltenango","Mixco","Villa Nueva","San Juan Sacatepéquez","Cobán","Escuintla"],
  "Guinea": ["Conakry","Nzérékoré","Kankan","Kindia","Labé","Guéckédou"],
  "Guinea-Bissau": ["Bissau","Bafatá","Gabú","Bissorã","Canchungo"],
  "Guyana": ["Georgetown","Linden","New Amsterdam","Anna Regina","Bartica"],
  "Haiti": ["Port-au-Prince","Cap-Haïtien","Delmas","Pétionville","Gonaïves","Les Cayes"],
  "Honduras": ["Tegucigalpa","San Pedro Sula","Choloma","La Ceiba","El Progreso","Danlí"],
  "Hungary": ["Budapest","Debrecen","Miskolc","Szeged","Pécs","Győr","Nyíregyháza","Kecskemét","Székesfehérvár","Szombathely"],
  "Iceland": ["Reykjavik","Kópavogur","Hafnarfjörður","Akureyri","Reykjanesbær","Garðabær"],
  "India": [
    // Maharashtra
    "Mumbai","Navi Mumbai","Thane","Kalyan-Dombivli","Vasai-Virar","Ulhasnagar",
    "Pune","Pimpri-Chinchwad","Nagpur","Nashik","Aurangabad","Solapur",
    "Kolhapur","Amravati","Jalgaon","Sangli","Satara","Ahmednagar","Dhule",
    "Malegaon","Latur","Akola","Nanded","Chandrapur","Yavatmal","Wardha",
    "Jalna","Osmanabad","Parbhani","Beed","Gondia","Hingoli","Buldhana",
    "Ratnagiri","Sindhudurg","Washim","Nandurbar","Gadchiroli","Bhandara",
    // Delhi NCR
    "Delhi","Noida","Ghaziabad","Gurugram","Faridabad","Greater Noida",
    "Dwarka","Rohini","Loni",
    // Karnataka
    "Bengaluru","Mysuru","Mangaluru","Hubli-Dharwad","Belagavi","Kalaburagi",
    "Davanagere","Tumakuru","Shivamogga","Udupi","Ballari","Vijayapura",
    "Bidar","Hassan","Chikkamagaluru","Dharwad","Raichur","Koppal",
    "Bagalkot","Mandya","Kodagu","Chitradurga","Haveri","Gadag","Yadgir",
    "Chamarajanagar","Chikkaballapur","Kolar","Ramanagara","Bengaluru Rural",
    // Telangana
    "Hyderabad","Warangal","Nizamabad","Karimnagar","Khammam","Ramagundam",
    "Nalgonda","Mahbubnagar","Sangareddy","Suryapet","Adilabad","Miryalaguda",
    "Siddipet","Jangaon","Jagtial","Mancherial","Nirmal","Peddapalli",
    "Wanaparthy","Mahabubabad","Mulugu","Nagarkurnool","Jogulamba","Vikarabad",
    // Tamil Nadu
    "Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli",
    "Vellore","Erode","Tiruppur","Thoothukudi","Dindigul","Thanjavur",
    "Nagercoil","Kanchipuram","Villupuram","Cuddalore","Krishnagiri",
    "Tiruvannamalai","Sivakasi","Karur","Namakkal","Virudhunagar","Tenkasi",
    "Pudukkottai","Ramanathapuram","Ooty","Kodaikanal","Hosur","Kumbakonam",
    "Nagapattinam","Theni","Ariyalur","Perambalur","Dharmapuri","Tiruvarur",
    "Nilgiris","Kallakurichi","Chengalpattu","Ranipet","Tirupathur",
    // West Bengal
    "Kolkata","Howrah","Asansol","Durgapur","Siliguri","Bardhaman","Haldia",
    "Kharagpur","Malda","Barasat","Kalyani","Jalpaiguri","Cooch Behar",
    "Berhampore","Raiganj","Puruliya","Bankura","Darjeeling","Bishnupur",
    "Tamluk","Krishnanagar","Alipurduar","Balurghat","Contai","Nabadwip",
    "Habra","Santiniketan","Midnapore","Murshidabad","Barrackpore",
    // Gujarat
    "Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar",
    "Gandhinagar","Anand","Nadiad","Morbi","Junagadh","Bharuch","Ankleshwar",
    "Vapi","Navsari","Bhuj","Porbandar","Mehsana","Surendranagar","Amreli",
    "Botad","Dahod","Godhra","Patan","Palanpur","Valsad","Dwarka",
    "Deesa","Gondal","Jetpur","Veraval","Wadhwan",
    // Rajasthan
    "Jaipur","Jodhpur","Udaipur","Kota","Ajmer","Bikaner","Alwar","Bhilwara",
    "Sikar","Sri Ganganagar","Nagaur","Barmer","Jaisalmer","Pali","Bharatpur",
    "Churu","Jhunjhunu","Sawai Madhopur","Tonk","Bundi","Jhalawar","Dungarpur",
    "Banswara","Dausa","Sirohi","Hanumangarh","Karauli","Dholpur","Rajsamand",
    "Baran","Pratapgarh","Jalore","Dhaulpur","Chittorgarh",
    // Uttar Pradesh
    "Lucknow","Kanpur","Agra","Varanasi","Prayagraj","Meerut","Ghaziabad",
    "Gorakhpur","Bareilly","Aligarh","Moradabad","Mathura","Ayodhya",
    "Saharanpur","Jhansi","Muzaffarnagar","Firozabad","Rampur","Hapur",
    "Rae Bareli","Etawah","Mainpuri","Farrukhabad","Lakhimpur Kheri",
    "Sitapur","Azamgarh","Ballia","Sultanpur","Unnao","Bahraich","Gonda",
    "Basti","Shahjahanpur","Hardoi","Fatehpur","Banda","Mirzapur","Sonbhadra",
    "Chandauli","Ambedkar Nagar","Ghazipur","Deoria","Kushinagar","Maharajganj",
    "Siddharthnagar","Sant Kabir Nagar","Balrampur","Shravasti",
    // Kerala
    "Kochi","Thiruvananthapuram","Kozhikode","Thrissur","Kollam","Kannur",
    "Alappuzha","Malappuram","Palakkad","Kottayam","Idukki","Wayanad",
    "Kasaragod","Pathanamthitta","Ernakulam","Thrippunithura","Perinthalmanna",
    "Thalassery","Tirur","Irinjalakuda","Chalakudy","Kothamangalam",
    // Punjab
    "Ludhiana","Amritsar","Jalandhar","Patiala","Mohali","Bathinda",
    "Hoshiarpur","Pathankot","Moga","Phagwara","Ferozepur","Sangrur",
    "Fatehgarh Sahib","Rupnagar","Nawanshahr","Tarn Taran","Gurdaspur",
    "Muktsar","Faridkot","Mansa","Barnala","Kapurthala","Abohar","Malerkotla",
    // Madhya Pradesh
    "Bhopal","Indore","Gwalior","Jabalpur","Ujjain","Sagar","Rewa",
    "Satna","Chhindwara","Dewas","Ratlam","Mandsaur","Burhanpur","Khandwa",
    "Hoshangabad","Vidisha","Morena","Shivpuri","Bhind","Guna","Neemuch",
    "Shajapur","Seoni","Balaghat","Narsinghpur","Harda","Raisen","Sehore",
    "Betul","Damoh","Panna","Tikamgarh","Chhatarpur","Ashoknagar","Datia",
    // Bihar
    "Patna","Gaya","Muzaffarpur","Bhagalpur","Purnia","Darbhanga",
    "Bihar Sharif","Arrah","Begusarai","Katihar","Sitamarhi","Samastipur",
    "Munger","Siwan","Chapra","Motihari","Hajipur","Kishanganj","Araria",
    "Nawada","Nalanda","Vaishali","Jehanabad","Buxar","Rohtas","Aurangabad",
    "Jamui","Lakhisarai","Sheikhpura","Supaul","Madhepura","Saharsah",
    "Madhubani","Sitamarhi","Sheohar","West Champaran","East Champaran",
    // Andhra Pradesh
    "Vijayawada","Visakhapatnam","Tirupati","Guntur","Nellore","Rajahmundry",
    "Kakinada","Kurnool","Eluru","Ongole","Nandyal","Chittoor","Kadapa",
    "Anantapur","Vizianagaram","Srikakulam","Hindupur","Dharmavaram",
    "Tadepalligudem","Machilipatnam","Proddatur","Adoni","Tadipatri",
    // Haryana
    "Rohtak","Panipat","Karnal","Hisar","Panchkula","Sonipat","Yamunanagar",
    "Ambala","Faridabad","Gurugram","Rewari","Bhiwani","Kurukshetra","Kaithal",
    "Jind","Sirsa","Fatehabad","Mahendragarh","Jhajjar","Palwal","Nuh",
    "Bahadurgarh","Narnaul","Hansi","Tohana",
    // Odisha
    "Bhubaneswar","Cuttack","Rourkela","Berhampur","Sambalpur","Puri",
    "Balasore","Baripada","Jharsuguda","Sundargarh","Angul","Jeypore",
    "Koraput","Kendujhar","Paradip","Rayagada","Bhawanipatna","Dhenkanal",
    "Phulbani","Bolangir","Sonepur","Nabarangpur","Malkangiri","Boudh",
    // Jharkhand
    "Ranchi","Jamshedpur","Dhanbad","Bokaro Steel City","Hazaribagh","Deoghar",
    "Giridih","Ramgarh","Dumka","Medininagar","Chakradharpur","Chaibasa",
    "Jamtara","Godda","Sahebganj","Pakur","Gumla","Lohardaga","Simdega",
    "Khunti","Latehar","Chatra","Koderma","Palamu",
    // Chhattisgarh
    "Raipur","Bhilai","Bilaspur","Durg","Korba","Rajnandgaon","Jagdalpur",
    "Raigarh","Ambikapur","Dhamtari","Mahasamund","Kabirdham","Kondagaon",
    "Jashpur","Kanker","Surguja","Balod","Bemetara","Gariaband","Mungeli",
    // Assam
    "Guwahati","Dibrugarh","Silchar","Jorhat","Nagaon","Tezpur","Tinsukia",
    "Lakhimpur","Golaghat","Sivasagar","Dhubri","Goalpara","Bongaigaon",
    "Barpeta","Nalbari","Darrang","Morigaon","Karbi Anglong","Karimganj",
    "Hailakandi","Dima Hasao","Majuli","Chirang","Baksa","Udalguri",
    // Uttarakhand
    "Dehradun","Haridwar","Rishikesh","Haldwani","Roorkee","Nainital",
    "Kashipur","Rudrapur","Mussoorie","Pithoragarh","Almora","Kotdwar",
    "Srinagar (Garhwal)","Uttarkashi","Tehri","Chamoli","Bageshwar",
    "Champawat","Pauri","Rudraprayag",
    // Jammu & Kashmir
    "Srinagar","Jammu","Anantnag","Baramulla","Sopore","Kupwara",
    "Pulwama","Udhampur","Rajouri","Poonch","Kathua","Doda","Ramban",
    "Reasi","Samba","Kishtwar","Bandipora","Ganderbal","Budgam","Kulgam","Shopian",
    // Himachal Pradesh
    "Shimla","Dharamsala","Mandi","Solan","Kullu","Baddi","Hamirpur",
    "Una","Bilaspur","Palampur","Nahan","Chamba","Kangra","Kinnaur",
    "Sirmaur","Lahaul and Spiti","Kasauli","Dalhousie","Manali","Kufri",
    // Goa
    "Panaji","Margao","Vasco da Gama","Mapusa","Ponda","Curchorem",
    "Calangute","Candolim","Baga","Pernem","Quepem",
    // Northeast states
    "Imphal","Churachandpur","Thoubal","Bishnupur (Manipur)",
    "Shillong","Tura","Jowai","Nongstoin",
    "Agartala","Dharmanagar","Udaipur (Tripura)","Belonia",
    "Aizawl","Lunglei","Serchhip","Champhai","Kolasib",
    "Kohima","Dimapur","Wokha","Tuensang","Mon","Zunheboto","Phek",
    "Itanagar","Naharlagun","Pasighat","Tawang","Ziro","Bomdila","Along",
    "Gangtok","Namchi","Gyalshing","Mangan","Jorethang",
    // Chandigarh
    "Chandigarh",
    // Union Territories
    "Puducherry","Karaikal","Yanam","Mahe",
    "Port Blair","Car Nicobar",
    "Leh","Kargil","Nubra","Zanskar",
    "Daman","Diu",
    "Silvassa","Dadra",
    "Kavaratti",
  ],
  "Indonesia": ["Jakarta","Surabaya","Bandung","Bekasi","Medan","Tangerang","Depok","Semarang","Palembang","Makassar","Bogor","Batam","Pekanbaru","Banjarmasin","Denpasar"],
  "Iran": ["Tehran","Mashhad","Isfahan","Karaj","Tabriz","Shiraz","Qom","Ahvaz","Kermanshah","Urmia","Rasht","Zahedan","Hamadan","Arak","Yazd"],
  "Iraq": ["Baghdad","Basra","Mosul","Erbil","Kirkuk","Sulaymaniyah","Najaf","Karbala","Fallujah","Ramadi"],
  "Ireland": ["Dublin","Cork","Limerick","Galway","Waterford","Drogheda","Dundalk","Swords","Bray","Navan","Ennis","Kilkenny"],
  "Israel": ["Tel Aviv","Jerusalem","Haifa","Rishon LeZion","Petah Tikva","Ashdod","Netanya","Beer Sheva","Holon","Bnei Brak","Ramat Gan"],
  "Italy": ["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Bari","Catania","Venice","Verona","Messina","Padua","Trieste"],
  "Jamaica": ["Kingston","Montego Bay","Portmore","Spanish Town","May Pen","Mandeville"],
  "Japan": ["Tokyo","Osaka","Nagoya","Sapporo","Fukuoka","Kobe","Kyoto","Kawasaki","Saitama","Hiroshima","Sendai","Chiba","Kitakyushu","Sakai","Niigata","Hamamatsu","Kumamoto","Sagamihara"],
  "Jordan": ["Amman","Zarqa","Irbid","Russeifa","Aqaba","Madaba","Jerash","Ajloun"],
  "Kazakhstan": ["Almaty","Astana","Shymkent","Aktobe","Karaganda","Taraz","Pavlodar","Semey","Oskemen","Uralsk"],
  "Kenya": ["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Thika","Malindi","Machakos","Kakamega"],
  "Kiribati": ["Tarawa","Betio","Bikenibeu"],
  "Kosovo": ["Pristina","Prizren","Peja","Mitrovica","Gjilan","Ferizaj"],
  "Kuwait": ["Kuwait City","Al Ahmadi","Hawalli","Salmiya","Jahra","Fahaheel","Mangaf"],
  "Kyrgyzstan": ["Bishkek","Osh","Jalal-Abad","Karakol","Tokmok","Uzgen","Naryn"],
  "Laos": ["Vientiane","Luang Prabang","Savannakhet","Pakse","Thakhek","Xam Neua"],
  "Latvia": ["Riga","Daugavpils","Jelgava","Jūrmala","Jēkabpils","Rēzekne","Valmiera","Ventspils"],
  "Lebanon": ["Beirut","Tripoli","Sidon","Tyre","Zahle","Jounieh","Nabatieh"],
  "Lesotho": ["Maseru","Teyateyaneng","Mafeteng","Hlotse","Mohale's Hoek"],
  "Liberia": ["Monrovia","Gbarnga","Kakata","Bensonville","Harper","Buchanan"],
  "Libya": ["Tripoli","Benghazi","Misrata","Tarhuna","Zawiya","Ajdabiya","Sabha"],
  "Liechtenstein": ["Vaduz","Schaan","Triesen","Balzers"],
  "Lithuania": ["Vilnius","Kaunas","Klaipėda","Šiauliai","Panevėžys","Alytus","Marijampolė"],
  "Luxembourg": ["Luxembourg City","Esch-sur-Alzette","Differdange","Dudelange","Ettelbruck"],
  "Madagascar": ["Antananarivo","Toamasina","Antsirabe","Fianarantsoa","Mahajanga","Toliara","Antsiranana"],
  "Malawi": ["Lilongwe","Blantyre","Mzuzu","Zomba","Kasungu","Mangochi"],
  "Malaysia": ["Kuala Lumpur","Johor Bahru","Ipoh","Shah Alam","Penang","Petaling Jaya","Subang Jaya","Kota Kinabalu","Kuching","Seremban","Melaka","Putrajaya","Kota Bharu"],
  "Maldives": ["Malé","Addu City","Fuvahmulah","Kulhudhuffushi"],
  "Mali": ["Bamako","Sikasso","Ségou","Koutiala","Gao","Kayes","Mopti"],
  "Malta": ["Valletta","Birkirkara","Mosta","Qormi","Naxxar","Żabbar","San Ġwann"],
  "Marshall Islands": ["Majuro","Ebeye"],
  "Mauritania": ["Nouakchott","Nouadhibou","Kiffa","Zouerate","Kaédi"],
  "Mauritius": ["Port Louis","Beau Bassin-Rose Hill","Vacoas-Phoenix","Curepipe","Quatre Bornes","Triolet"],
  "Mexico": ["Mexico City","Guadalajara","Monterrey","Puebla","Tijuana","León","Juárez","Zapopan","Mérida","San Luis Potosí","Aguascalientes","Querétaro","Hermosillo","Mexicali","Culiacán"],
  "Micronesia": ["Palikir","Weno","Kolonia","Lelu"],
  "Moldova": ["Chișinău","Tiraspol","Bălți","Bender","Rîbnița","Cahul"],
  "Monaco": ["Monaco","Monte Carlo","La Condamine","Fontvieille"],
  "Mongolia": ["Ulaanbaatar","Erdenet","Darkhan","Choibalsan","Mörön"],
  "Montenegro": ["Podgorica","Nikšić","Bar","Herceg Novi","Bijelo Polje","Cetinje"],
  "Morocco": ["Casablanca","Rabat","Fez","Marrakesh","Agadir","Tangier","Meknès","Oujda","Kenitra","Tétouan"],
  "Mozambique": ["Maputo","Matola","Nampula","Beira","Chimoio","Nacala","Quelimane","Tete"],
  "Myanmar": ["Yangon","Mandalay","Naypyidaw","Mawlamyine","Bago","Pathein","Monywa","Taunggyi"],
  "Namibia": ["Windhoek","Rundu","Walvis Bay","Oshakati","Swakopmund","Katima Mulilo","Grootfontein"],
  "Nauru": ["Yaren","Denigomodu","Aiwo","Boe"],
  "Nepal": ["Kathmandu","Pokhara","Lalitpur","Biratnagar","Bharatpur","Birgunj","Butwal","Dharan","Hetauda","Bhaktapur"],
  "Netherlands": ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Tilburg","Groningen","Breda","Nijmegen","Enschede","Apeldoorn","Haarlem","Arnhem"],
  "New Zealand": ["Auckland","Wellington","Christchurch","Hamilton","Tauranga","Napier-Hastings","Dunedin","Palmerston North","Nelson","Rotorua"],
  "Nicaragua": ["Managua","León","Masaya","Matagalpa","Chinandega","Estelí","Granada"],
  "Niger": ["Niamey","Zinder","Maradi","Agadez","Tahoua","Dosso"],
  "Nigeria": ["Lagos","Abuja","Kano","Ibadan","Port Harcourt","Benin City","Kaduna","Enugu","Onitsha","Aba","Abeokuta","Ilorin","Jos","Maiduguri","Calabar","Warri"],
  "North Korea": ["Pyongyang","Hamhung","Chongjin","Nampo","Wonsan","Sinuiju"],
  "North Macedonia": ["Skopje","Bitola","Kumanovo","Tetovo","Veles","Ohrid"],
  "Norway": ["Oslo","Bergen","Trondheim","Stavanger","Drammen","Fredrikstad","Kristiansand","Sandnes","Tromsø","Sarpsborg"],
  "Oman": ["Muscat","Salalah","Sohar","Nizwa","Sur","Ibri","Khasab"],
  "Pakistan": ["Karachi","Lahore","Faisalabad","Rawalpindi","Islamabad","Gujranwala","Peshawar","Multan","Hyderabad","Quetta","Sialkot","Bahawalpur","Sargodha","Gujrat"],
  "Palau": ["Ngerulmud","Koror","Airai"],
  "Palestine": ["Gaza","Ramallah","Nablus","Hebron","Jenin","Jericho","Bethlehem","Tulkarm"],
  "Panama": ["Panama City","Colón","David","La Chorrera","San Miguelito","Chitré"],
  "Papua New Guinea": ["Port Moresby","Lae","Mount Hagen","Madang","Wewak","Goroka"],
  "Paraguay": ["Asunción","Ciudad del Este","Luque","San Lorenzo","Capiatá","Lambaré","Encarnación"],
  "Peru": ["Lima","Arequipa","Trujillo","Chiclayo","Piura","Iquitos","Cusco","Chimbote","Huancayo","Tacna"],
  "Philippines": ["Manila","Quezon City","Davao","Caloocan","Zamboanga","Cebu","Antipolo","Pasig","Taguig","Valenzuela","Makati","Marikina","Bacolod"],
  "Poland": ["Warsaw","Kraków","Łódź","Wrocław","Poznań","Gdańsk","Szczecin","Bydgoszcz","Lublin","Katowice","Białystok","Gdynia","Częstochowa"],
  "Portugal": ["Lisbon","Porto","Braga","Setúbal","Coimbra","Funchal","Almada","Aveiro","Agualva-Cacém","Viseu"],
  "Qatar": ["Doha","Al Wakrah","Al Khor","Lusail","Madinat ash Shamal","Al Rayyan"],
  "Romania": ["Bucharest","Cluj-Napoca","Timișoara","Iași","Constanța","Craiova","Brașov","Galați","Ploiești","Oradea"],
  "Russia": ["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg","Nizhny Novgorod","Kazan","Chelyabinsk","Omsk","Samara","Rostov-on-Don","Ufa","Krasnoyarsk","Perm","Voronezh","Volgograd"],
  "Rwanda": ["Kigali","Butare","Gitarama","Ruhengeri","Gisenyi","Byumba"],
  "Saint Kitts and Nevis": ["Basseterre","Charlestown","Sandy Point","Cayon"],
  "Saint Lucia": ["Castries","Bisee","Vieux Fort","Micoud"],
  "Saint Vincent and the Grenadines": ["Kingstown","Georgetown","Barrouallie","Port Elizabeth"],
  "Samoa": ["Apia","Salelologa","Faleasiu"],
  "San Marino": ["San Marino City","Serravalle","Borgo Maggiore"],
  "São Tomé and Príncipe": ["São Tomé","Santo António","Santana"],
  "Saudi Arabia": ["Riyadh","Jeddah","Mecca","Medina","Dammam","Khobar","Tabuk","Taif","Buraidah","Khamis Mushait","Abha","Najran"],
  "Senegal": ["Dakar","Touba","Thiès","Saint-Louis","Ziguinchor","Kaolack","Mbour"],
  "Serbia": ["Belgrade","Novi Sad","Niš","Kragujevac","Subotica","Pančevo","Čačak","Novi Pazar"],
  "Seychelles": ["Victoria","Anse Boileau","Beau Vallon","Bel Ombre"],
  "Sierra Leone": ["Freetown","Koidu","Bo","Kenema","Makeni","Lunsar"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava","Košice","Prešov","Žilina","Banská Bystrica","Nitra","Trnava","Martin"],
  "Slovenia": ["Ljubljana","Maribor","Celje","Kranj","Koper","Velenje","Novo Mesto"],
  "Solomon Islands": ["Honiara","Auki","Gizo","Tulagi"],
  "Somalia": ["Mogadishu","Hargeisa","Merca","Bosaso","Kismayo","Baidoa","Berbera"],
  "South Africa": ["Johannesburg","Cape Town","Durban","Pretoria","Port Elizabeth","Bloemfontein","East London","Nelspruit","Polokwane","Kimberley","Soweto","Pietermaritzburg"],
  "South Korea": ["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju","Suwon","Ulsan","Changwon","Seongnam","Yongin","Goyang","Bucheon"],
  "South Sudan": ["Juba","Wau","Malakal","Yei","Aweil","Torit"],
  "Spain": ["Madrid","Barcelona","Valencia","Seville","Zaragoza","Málaga","Murcia","Palma","Las Palmas","Bilbao","Alicante","Córdoba","Valladolid","Vigo","Gijón","Granada"],
  "Sri Lanka": ["Colombo","Kandy","Galle","Jaffna","Negombo","Kurunegala","Ratnapura","Trincomalee","Badulla","Matara"],
  "Sudan": ["Khartoum","Omdurman","Khartoum North","Port Sudan","Kassala","Obeid","Wad Medani"],
  "Suriname": ["Paramaribo","Lelydorp","Nieuw Nickerie","Moengo","Marienburg"],
  "Sweden": ["Stockholm","Gothenburg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Jönköping","Norrköping","Lund","Umeå"],
  "Switzerland": ["Zurich","Geneva","Basel","Bern","Lausanne","Winterthur","Lucerne","St. Gallen","Lugano","Biel/Bienne"],
  "Syria": ["Damascus","Aleppo","Homs","Latakia","Deir ez-Zor","Raqqa","Daraa","Tartus"],
  "Taiwan": ["Taipei","Kaohsiung","Taichung","Tainan","Taoyuan","Hsinchu","Keelung","Chiayi"],
  "Tajikistan": ["Dushanbe","Khujand","Kulob","Qŭrghonteppa","Istaravshan","Konibodom"],
  "Tanzania": ["Dar es Salaam","Dodoma","Mwanza","Arusha","Mbeya","Morogoro","Tanga","Zanzibar City","Kigoma"],
  "Thailand": ["Bangkok","Chiang Mai","Pattaya","Hat Yai","Nonthaburi","Udon Thani","Nakhon Ratchasima","Khon Kaen","Chon Buri","Ubon Ratchathani"],
  "Timor-Leste": ["Dili","Baucau","Lospalos","Maliana","Ermera"],
  "Togo": ["Lomé","Sokodé","Kara","Kpalimé","Atakpamé","Dapaong"],
  "Tonga": ["Nukuʻalofa","Neiafu","Haveluloto"],
  "Trinidad and Tobago": ["Port of Spain","San Fernando","Chaguanas","Arima","Point Fortin"],
  "Tunisia": ["Tunis","Sfax","Sousse","Kairouan","Bizerte","Gabès","Ariana","Gafsa","El Adem"],
  "Turkey": ["Istanbul","Ankara","Izmir","Bursa","Adana","Gaziantep","Konya","Antalya","Mersin","Diyarbakır","Kayseri","Eskişehir","Samsun","Denizli","Malatya"],
  "Turkmenistan": ["Ashgabat","Türkmenabat","Mary","Balkanabat","Daşoguz"],
  "Tuvalu": ["Funafuti","Savave","Tanrake"],
  "Uganda": ["Kampala","Gulu","Lira","Mbarara","Jinja","Mbale","Masaka","Entebbe"],
  "Ukraine": ["Kyiv","Kharkiv","Odessa","Dnipro","Donetsk","Zaporizhzhia","Lviv","Kryvyi Rih","Mykolaiv","Mariupol","Chernivtsi","Sumy","Poltava","Khmelnytskyi"],
  "United Arab Emirates": ["Dubai","Abu Dhabi","Sharjah","Ajman","Ras Al Khaimah","Fujairah","Al Ain"],
  "United Kingdom": ["London","Manchester","Birmingham","Glasgow","Liverpool","Leeds","Sheffield","Edinburgh","Bristol","Cardiff","Newcastle","Belfast","Nottingham","Leicester","Southampton","Oxford","Cambridge","Brighton"],
  "United States": ["New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio","San Diego","Dallas","San Jose","Austin","San Francisco","Seattle","Denver","Nashville","Boston","Atlanta","Miami","Portland","Las Vegas","Washington DC","Minneapolis","Detroit","Charlotte","Orlando","Sacramento","Indianapolis","Columbus","Fort Worth","Memphis"],
  "Uruguay": ["Montevideo","Salto","Ciudad de la Costa","Paysandú","Las Piedras","Rivera","Canelones"],
  "Uzbekistan": ["Tashkent","Samarkand","Namangan","Andijan","Bukhara","Nukus","Fergana","Kokand"],
  "Vanuatu": ["Port Vila","Luganville","Norsup"],
  "Vatican City": ["Vatican City"],
  "Venezuela": ["Caracas","Maracaibo","Valencia","Barquisimeto","Maracay","Ciudad Guayana","San Cristóbal","Maturín","Barcelona","Cumana"],
  "Vietnam": ["Ho Chi Minh City","Hanoi","Da Nang","Hai Phong","Can Tho","Bien Hoa","Nha Trang","Hue","Buon Ma Thuot","Vung Tau"],
  "Yemen": ["Sanaa","Aden","Taiz","Al Hudaydah","Mukalla","Ibb","Dhamar"],
  "Zambia": ["Lusaka","Kitwe","Ndola","Kabwe","Chingola","Mufulira","Livingstone"],
  "Zimbabwe": ["Harare","Bulawayo","Chitungwiza","Mutare","Gweru","Kwekwe","Kadoma"],
};
